export const SET_PUZZLE_CONSTRUCTOR = 'SET_PUZZLE_CONSTRUCTOR';

export const SET_HINT_PREFERENCE = 'SET_HINT_PREFERENCE';

export const LETTER_PRESS = "LETTER_PRESS";

export const RESET_GUESSES = "RESET_GUESSES"

export const CURRENT_WORD_PROGRESS = "CURRENT_WORD_PROGRESS";

export const FINALIZE_WORD = "FINALIZE_WORD";

export const CORRECT_MAP = "CORRECT_MAP";